// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Layout: typeof import('./src/components/layout.vue')['default']
    Page: typeof import('./src/components/page.vue')['default']
    PageTitle: typeof import('./src/components/pageTitle.vue')['default']
    PortTable: typeof import('./src/components/port-list/port-table.vue')['default']
    RichText: typeof import('./src/components/RichText.vue')['default']
    RoomTable: typeof import('./src/components/room-list/room-table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteTable: typeof import('./src/components/site-list/site-table.vue')['default']
    SliderBar: typeof import('./src/components/sliderBar.vue')['default']
    Switch: typeof import('./src/components/switch.vue')['default']
    Table: typeof import('./src/components/site-online/table.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    Ws: typeof import('./src/components/ws.vue')['default']
  }
}

export {}
